### PR TITLE
Add simple marshal saving for dictionary

### PR DESCRIPTION
**Pull request by a-fent**

### CODE REVIEW

**Comment by inukshuk** [comment]
Interesting! Do you think it would make sense to use this dictionary by default to lower the installation barrier?

**Comment by a-fent** [comment]
Possibly, yes. I think Marshal is among the fastest disk persistence options. It saves time for me compared to re-reading the zip (1.5s -> 0.2s).

 

The main disadvantage is that Marshalled files are IIRC not portable, but this is an end product generated only on the user’s computer so it doesn’t matter

 

 

Von: Sylvester Keil [mailto:notifications@github.com] 
Gesendet: Donnerstag, 29. März 2018 17:15
An: inukshuk/anystyle
Cc: Alex Fenton; Author
Betreff: Re: [inukshuk/anystyle] Add simple marshal saving for dictionary (#107)

 

Interesting! Do you think it would make sense to use this dictionary by default to lower the installation barrier?

**Comment by inukshuk** [comment]
I've made this the new default; the size on disk is much smaller than the GDBM file so the only real downside is memory-footprint of keeping the entire dictionary in memory. If that's a problem people can use GDBM or Redis instead.

**Comment by a-fent** [comment]
Sounds good. And great to see all the commits and tidying up of issues - thanks for all your work.

**Pull request merged**
